name: 'Aztec Setup'
description: 'Setup Aztec and Nargo'
inputs:
  enable-caching:
    description: 'Enable Docker image caching (default: true)'
    required: false
    default: 'true'
  aztec-version:
    description: 'Aztec Version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Response Cached Images
      if: inputs.enable-caching == 'true'
      id: cache-docker-aztec
      uses: actions/cache@v3
      with:
          path: ci/cache/docker/aztec
          key: cache-docker-aztec-${{ inputs.aztec-version }}

    - name: Cache Miss
      if: inputs.enable-caching == 'true' && steps.cache-docker-aztec.outputs.cache-hit != 'true'
      shell: bash
      run: |
        docker pull aztecprotocol/aztec:${{ inputs.aztec-version }}
        docker pull aztecprotocol/aztec-nargo:${{ inputs.aztec-version }}
        docker pull aztecprotocol/cli-wallet:${{ inputs.aztec-version }}
        mkdir -p ci/cache/docker/aztec
        docker image save aztecprotocol/aztec:${{ inputs.aztec-version }} --output ./ci/cache/docker/aztec/aztec-${{ inputs.aztec-version }}.tar
        docker image save aztecprotocol/aztec-nargo:${{ inputs.aztec-version }} --output ./ci/cache/docker/aztec/aztec-nargo-${{ inputs.aztec-version }}.tar
        docker image save aztecprotocol/cli-wallet:${{ inputs.aztec-version }} --output ./ci/cache/docker/aztec/cli-wallet-${{ inputs.aztec-version }}.tar

    - name: Cache Hit
      if: inputs.enable-caching == 'true' && steps.cache-docker-aztec.outputs.cache-hit == 'true'
      shell: bash
      run: |
        docker image load --input ./ci/cache/docker/aztec/aztec-${{ inputs.aztec-version }}.tar
        docker image load --input ./ci/cache/docker/aztec/aztec-nargo-${{ inputs.aztec-version }}.tar
        docker image load --input ./ci/cache/docker/aztec/cli-wallet-${{ inputs.aztec-version }}.tar

    - name: Install Aztec
      shell: bash
      run: |
        curl -s https://install.aztec.network | NON_INTERACTIVE=1 VERSION=${{ inputs.aztec-version }} bash -s
        echo "/home/runner/.aztec/bin" >> $GITHUB_PATH
